<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-07 22:12
=======
# Generated by Django 5.2.6 on 2025-09-05 19:09
>>>>>>> 1e278e88ee8e8527d8eecf55460631878dc1ba0e

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time_log', models.DateTimeField(help_text='Enter the date and time in the format: YYYY-MM-DD HH:MM:SS')),
=======
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
>>>>>>> 1e278e88ee8e8527d8eecf55460631878dc1ba0e
            ],
        ),
    ]
