# Generated by Django 5.2.5 on 2025-09-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time_log', models.DateTimeField(help_text='Enter the date and time in the format: YYYY-MM-DD HH:MM:SS')),
            ],
        ),
    ]
